title: New Musical Theatre Exchange
description: "Bringing together committed musical theatre writers in the Twin Cities"
url: "https://charlestbetz.github.io"
baseurl: "/nmte.org"

theme: minima

collections:
  events:
    output: true
    permalink: /events/:path/
  news:
    output: true
    permalink: /news/:path/

header_pages:
  - events.md
  - news.md
  - about.md
  - blog.md
  - community.md

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - admin
