title: New Musical Theatre Exchange
description: "Bringing together committed musical theatre writers in the Twin Cities"
url: "https://charlestbetz.github.io"
baseurl: "/nmte.org"

theme: minima

# Collections
collections:
  musicals:
    output: true
    permalink: /our-work/:path/

header_pages:
  - our-work.md
  - about.md
  - updates.md
  - blog.md
  - community.md

# Using custom permalinks based on post type - see _layouts/post.html
# Events: /events/YYYY/MM/DD/title/  
# News: /news/YYYY/MM/DD/title/

defaults:
  - scope:
      path: ""
      type: "musicals"
    values:
      layout: "musical"

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - admin
